name: Test

on: [pull_request]

jobs:
  run:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        php-versions: ['8.0', '8.1']
        symfony-versions: ['~4.4', '~5.4', '~6.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Composer install and lock symfony
        run: |
          export SYMFONY_REQUIRE=${{ matrix.symfony-versions }} \
          && composer install --prefer-dist --no-progress \
          && composer require symfony/flex '^2.2' \
          && composer update symfony/flex --no-plugins --no-scripts
